spring.application.name=netflix-backend

# Database Server Configuration
spring.datasource.url=jdbc:mysql://mysql-db:3306/netflix_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Sudeep@2k3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Lifecycle Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true